package com.clothesapp.view;

import com.clothesapp.model.ClothesModel;
import com.clothesapp.util.Validationutil;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Iterator;



/**
 *
 * @author Rose khatiwada
 * @ LMU ID: 23048677
 */
public class OhlanasWears extends javax.swing.JFrame {
    private ArrayList<ClothesModel> clothesList = new ArrayList();
    private java.awt.CardLayout cardLayout;
    private DefaultTableModel clothesTableModel;




    /**
     * Creates new form ClothesApp
     */
    public OhlanasWears() {
        initComponents();
        initializeData(); // Initialize clothes data and table
        initializeLayout(); // Set up CardLayout and add screens
        startProgress(); // Show loading screen and initiate progress
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        tabPaneMain = new javax.swing.JTabbedPane();
        Homepage = new javax.swing.JPanel();
        lblhomecollection = new javax.swing.JLabel();
        lblhomebest = new javax.swing.JLabel();
        lblheading = new javax.swing.JLabel();
        lblsubheading = new javax.swing.JLabel();
        lblparag = new javax.swing.JLabel();
        lblparaglinetwo = new javax.swing.JLabel();
        lblparaglinethree = new javax.swing.JLabel();
        lblparaglinefour = new javax.swing.JLabel();
        lblhomeimage = new javax.swing.JLabel();
        pnlClothes = new javax.swing.JPanel();
        tabPaneClothes = new javax.swing.JTabbedPane();
        lbltabClothes = new javax.swing.JLabel();
        jScrollPaneClothestable = new javax.swing.JScrollPane();
        tblClothes = new javax.swing.JTable();
        pnlAdminControl = new javax.swing.JPanel();
        lblProductManagement = new javax.swing.JLabel();
        txtFldProductCode = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtFldProductName = new javax.swing.JTextField();
        txtFldProductType = new javax.swing.JTextField();
        txtFldColor = new javax.swing.JTextField();
        txtFldStock = new javax.swing.JTextField();
        txtFldPrice = new javax.swing.JTextField();
        AboutUs = new javax.swing.JPanel();
        lblaboutusHeading = new javax.swing.JLabel();
        lblaboutusSubHeading = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        lblaboutus = new javax.swing.JLabel();
        lblsecondline = new javax.swing.JLabel();
        lblthirdline = new javax.swing.JLabel();
        lblfourthline = new javax.swing.JLabel();
        lblfifthline = new javax.swing.JLabel();
        lblsecondparagraph = new javax.swing.JLabel();
        lblsecparagLinetwo = new javax.swing.JLabel();
        lblsecparagLinethree = new javax.swing.JLabel();
        ContactUs = new javax.swing.JPanel();
        lblContactsubheading = new javax.swing.JLabel();
        lblcontactusSub = new javax.swing.JLabel();
        pnlspeakwithus = new javax.swing.JPanel();
        pnlContactdetails4 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblInstalogo = new javax.swing.JLabel();
        lblinstaID = new javax.swing.JLabel();
        lblFacebooklogo = new javax.swing.JLabel();
        lblfbID = new javax.swing.JLabel();
        lblmaillogo = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblphonelogo = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblSocialMedia4 = new javax.swing.JLabel();
        lblContactinfo = new javax.swing.JLabel();
        pnlInquaries = new javax.swing.JPanel();
        pnlinquariess = new javax.swing.JPanel();
        lblworkinghourlogo = new javax.swing.JLabel();
        lblmaillogo1 = new javax.swing.JLabel();
        lblpartnershipmail = new javax.swing.JLabel();
        lblworkinghours = new javax.swing.JLabel();
        lblinquaries = new javax.swing.JLabel();
        lblpartnershipcontact = new javax.swing.JLabel();
        lblpartnership = new javax.swing.JLabel();
        lblSaturday = new javax.swing.JLabel();
        lblMontofri = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblworkinghourlogo1 = new javax.swing.JLabel();
        lblClosed = new javax.swing.JLabel();
        pnlMainBar = new javax.swing.JPanel();
        lblMainBarSlogan = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblcopyrightfooter = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        pnlLoginScreen = new javax.swing.JPanel();
        pnlLoginLeft = new javax.swing.JPanel();
        iblloginimage = new javax.swing.JLabel();
        iblLoginslogan = new javax.swing.JLabel();
        iblLoginsloganlook = new javax.swing.JLabel();
        lblOhlana = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginSubTitle = new javax.swing.JLabel();
        txtFldUserName = new javax.swing.JTextField();
        lblLoginForgotPwd = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pwdFldLogin = new javax.swing.JPasswordField();
        lblLoginError = new javax.swing.JLabel();
        pnlLoadingScreen = new javax.swing.JPanel();
        pgBarSplashScreen = new javax.swing.JProgressBar(0,100);
        lblLoading = new javax.swing.JLabel();
        Logoo = new javax.swing.JLabel();

        pnlMainScreen.setBackground(new java.awt.Color(153, 153, 153));
        pnlMainScreen.setPreferredSize(new java.awt.Dimension(807, 600));

        pnlMain.setBackground(new java.awt.Color(153, 153, 153));
        pnlMain.setPreferredSize(new java.awt.Dimension(471, 601));

        tabPaneMain.setBackground(new java.awt.Color(51, 51, 51));
        tabPaneMain.setForeground(new java.awt.Color(153, 153, 153));
        tabPaneMain.setPreferredSize(new java.awt.Dimension(472, 500));

        Homepage.setBackground(new java.awt.Color(153, 153, 153));
        Homepage.setPreferredSize(new java.awt.Dimension(807, 433));

        lblhomecollection.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 60)); // NOI18N
        lblhomecollection.setText("collection");

        lblhomebest.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        lblhomebest.setText("Best ");

        lblheading.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        lblheading.setForeground(new java.awt.Color(102, 0, 51));
        lblheading.setText("2024");

        lblsubheading.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsubheading.setForeground(new java.awt.Color(93, 88, 88));
        lblsubheading.setText("Winter Sale | Upto 20% OFF");

        lblparag.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lblparag.setForeground(new java.awt.Color(51, 51, 51));
        lblparag.setText("At Oh-Lana's Wear, we bring you fashion that adapts to ");

        lblparaglinetwo.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lblparaglinetwo.setForeground(new java.awt.Color(51, 51, 51));
        lblparaglinetwo.setText("every season. Whether you're basking in the summer sun");

        lblparaglinethree.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lblparaglinethree.setForeground(new java.awt.Color(51, 51, 51));
        lblparaglinethree.setText("sun or cozying up in winter, our collection has something");

        lblparaglinefour.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lblparaglinefour.setForeground(new java.awt.Color(51, 51, 51));
        lblparaglinefour.setText("for every occasion.");

        lblhomeimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/homepage.png"))); // NOI18N

        javax.swing.GroupLayout HomepageLayout = new javax.swing.GroupLayout(Homepage);
        Homepage.setLayout(HomepageLayout);
        HomepageLayout.setHorizontalGroup(
            HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepageLayout.createSequentialGroup()
                .addGroup(HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomepageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblhomecollection)
                            .addComponent(lblhomebest)
                            .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(HomepageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblparaglinetwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblparag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblparaglinethree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)))
                    .addGroup(HomepageLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblsubheading, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomepageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblparaglinefour)))
                .addGap(30, 30, 30)
                .addComponent(lblhomeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        HomepageLayout.setVerticalGroup(
            HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepageLayout.createSequentialGroup()
                .addGroup(HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblhomeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomepageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhomebest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblhomecollection, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsubheading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblparag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblparaglinetwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblparaglinethree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblparaglinefour)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        tabPaneMain.addTab("Home Page", Homepage);

        pnlClothes.setBackground(new java.awt.Color(153, 153, 153));

        tabPaneClothes.setBackground(new java.awt.Color(90, 89, 89));
        tabPaneClothes.setForeground(new java.awt.Color(153, 153, 153));
        tabPaneClothes.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        lbltabClothes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbltabClothes.setForeground(new java.awt.Color(51, 51, 51));
        lbltabClothes.setText(" Clothes Information");
        lbltabClothes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        tblClothes.setBackground(new java.awt.Color(102, 102, 102));
        tblClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Product Type", "Color", "Stock", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneClothestable.setViewportView(tblClothes);
        if (tblClothes.getColumnModel().getColumnCount() > 0) {
            tblClothes.getColumnModel().getColumn(0).setResizable(false);
            tblClothes.getColumnModel().getColumn(1).setResizable(false);
            tblClothes.getColumnModel().getColumn(2).setResizable(false);
            tblClothes.getColumnModel().getColumn(3).setResizable(false);
            tblClothes.getColumnModel().getColumn(4).setResizable(false);
            tblClothes.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pnlClothesLayout = new javax.swing.GroupLayout(pnlClothes);
        pnlClothes.setLayout(pnlClothesLayout);
        pnlClothesLayout.setHorizontalGroup(
            pnlClothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClothesLayout.createSequentialGroup()
                .addGroup(pnlClothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabPaneClothes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addGroup(pnlClothesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlClothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneClothestable)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlClothesLayout.createSequentialGroup()
                                .addComponent(lbltabClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlClothesLayout.setVerticalGroup(
            pnlClothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClothesLayout.createSequentialGroup()
                .addComponent(tabPaneClothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltabClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneClothestable, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneMain.addTab("Clothes", pnlClothes);

        pnlAdminControl.setBackground(new java.awt.Color(153, 153, 153));

        lblProductManagement.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblProductManagement.setForeground(new java.awt.Color(51, 51, 51));
        lblProductManagement.setText("PRODUCT MANAGEMENT");

        txtFldProductCode.setBackground(new java.awt.Color(51, 51, 51));
        txtFldProductCode.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldProductCode.setForeground(new java.awt.Color(153, 153, 153));
        txtFldProductCode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Product Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldProductCode.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProductCodeActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(204, 204, 204));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(204, 204, 204));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtFldProductName.setBackground(new java.awt.Color(51, 51, 51));
        txtFldProductName.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldProductName.setForeground(new java.awt.Color(153, 153, 153));
        txtFldProductName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Product Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldProductName.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProductNameActionPerformed(evt);
            }
        });

        txtFldProductType.setBackground(new java.awt.Color(51, 51, 51));
        txtFldProductType.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldProductType.setForeground(new java.awt.Color(153, 153, 153));
        txtFldProductType.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Product Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldProductType.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProductTypeActionPerformed(evt);
            }
        });

        txtFldColor.setBackground(new java.awt.Color(51, 51, 51));
        txtFldColor.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldColor.setForeground(new java.awt.Color(153, 153, 153));
        txtFldColor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldColor.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldColorActionPerformed(evt);
            }
        });

        txtFldStock.setBackground(new java.awt.Color(51, 51, 51));
        txtFldStock.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldStock.setForeground(new java.awt.Color(153, 153, 153));
        txtFldStock.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldStock.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldStockActionPerformed(evt);
            }
        });

        txtFldPrice.setBackground(new java.awt.Color(51, 51, 51));
        txtFldPrice.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        txtFldPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtFldPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldPrice.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminControlLayout = new javax.swing.GroupLayout(pnlAdminControl);
        pnlAdminControl.setLayout(pnlAdminControlLayout);
        pnlAdminControlLayout.setHorizontalGroup(
            pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminControlLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(pnlAdminControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductManagement)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAdminControlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        pnlAdminControlLayout.setVerticalGroup(
            pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        tabPaneMain.addTab("Admin Control", pnlAdminControl);

        AboutUs.setBackground(new java.awt.Color(153, 153, 153));
        AboutUs.setPreferredSize(new java.awt.Dimension(807, 433));

        lblaboutusHeading.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblaboutusHeading.setForeground(new java.awt.Color(51, 51, 51));
        lblaboutusHeading.setText("Unveiling Your Unique");

        lblaboutusSubHeading.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        lblaboutusSubHeading.setForeground(new java.awt.Color(51, 51, 51));
        lblaboutusSubHeading.setText("Fashion Journey");

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-13 163201.png"))); // NOI18N
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        lblaboutus.setForeground(new java.awt.Color(51, 51, 51));
        lblaboutus.setText("At Oh-lana's wears, we’re all about making every season ");

        lblsecondline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsecondline.setForeground(new java.awt.Color(51, 51, 51));
        lblsecondline.setText("your favorite. For summer we bring you lightweight, ");

        lblthirdline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblthirdline.setForeground(new java.awt.Color(51, 51, 51));
        lblthirdline.setText("breathable styles perfect for sunny days and beach vibes.");

        lblfourthline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblfourthline.setForeground(new java.awt.Color(51, 51, 51));
        lblfourthline.setText("When winter rolls around, our cozy, warm pieces keep you");

        lblfifthline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblfifthline.setForeground(new java.awt.Color(51, 51, 51));
        lblfifthline.setText("bundled up and looking great.");

        lblsecondparagraph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsecondparagraph.setForeground(new java.awt.Color(51, 51, 51));
        lblsecondparagraph.setText("We’re here to help you feel comfortable, confident, and ");

        lblsecparagLinetwo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsecparagLinetwo.setForeground(new java.awt.Color(51, 51, 51));
        lblsecparagLinetwo.setText("stylish no matter the weather. Because seasons change, but");

        lblsecparagLinethree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsecparagLinethree.setForeground(new java.awt.Color(51, 51, 51));
        lblsecparagLinethree.setText("great style never goes out of fashion!");

        javax.swing.GroupLayout AboutUsLayout = new javax.swing.GroupLayout(AboutUs);
        AboutUs.setLayout(AboutUsLayout);
        AboutUsLayout.setHorizontalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblaboutus)
                    .addComponent(lblsecondline)
                    .addComponent(lblthirdline)
                    .addComponent(lblfourthline)
                    .addComponent(lblfifthline)
                    .addComponent(lblsecondparagraph)
                    .addComponent(lblaboutusHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblaboutusSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsecparagLinetwo)
                    .addComponent(lblsecparagLinethree))
                .addGap(25, 25, 25)
                .addComponent(lblimage)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        AboutUsLayout.setVerticalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblaboutusHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblaboutusSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblaboutus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsecondline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthirdline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfourthline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfifthline)
                .addGap(29, 29, 29)
                .addComponent(lblsecondparagraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsecparagLinetwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsecparagLinethree)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabPaneMain.addTab("About Us", AboutUs);

        ContactUs.setBackground(new java.awt.Color(153, 153, 153));
        ContactUs.setPreferredSize(new java.awt.Dimension(807, 433));

        lblContactsubheading.setBackground(new java.awt.Color(51, 51, 51));
        lblContactsubheading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactsubheading.setForeground(new java.awt.Color(90, 85, 85));
        lblContactsubheading.setText("We’d love to hear from you! Whether you have questions about our collections, sizing, or orders, we’re here to help.");

        lblcontactusSub.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblcontactusSub.setForeground(new java.awt.Color(51, 51, 51));
        lblcontactusSub.setText("Don't Hesitate To Contact Us");

        pnlspeakwithus.setBackground(new java.awt.Color(102, 102, 102));

        pnlContactdetails4.setBackground(new java.awt.Color(255, 255, 255));

        lblEmail.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("Email ");

        lblPhone.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(102, 102, 102));
        lblPhone.setText("Phone ");

        lblInstalogo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblInstalogo.setForeground(new java.awt.Color(102, 102, 102));
        lblInstalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 115128.png"))); // NOI18N

        lblinstaID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblinstaID.setForeground(new java.awt.Color(153, 153, 153));
        lblinstaID.setText("@Oh-lana's Wears");

        lblFacebooklogo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblFacebooklogo.setForeground(new java.awt.Color(102, 102, 102));
        lblFacebooklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 115249.png"))); // NOI18N

        lblfbID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblfbID.setForeground(new java.awt.Color(153, 153, 153));
        lblfbID.setText("Oh-lana's Wears");

        lblmaillogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 113533.png"))); // NOI18N

        lblemail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblemail.setForeground(new java.awt.Color(153, 153, 153));
        lblemail.setText("supportohlana'swears@gmail.com");

        lblphonelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 114501.png"))); // NOI18N
        lblphonelogo.setText("jLabel1");

        lblphone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblphone.setForeground(new java.awt.Color(153, 153, 153));
        lblphone.setText("+977 9804568970");

        lblSocialMedia4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        lblSocialMedia4.setForeground(new java.awt.Color(51, 51, 51));
        lblSocialMedia4.setText("Social Media");

        lblContactinfo.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        lblContactinfo.setForeground(new java.awt.Color(51, 51, 51));
        lblContactinfo.setText("Speak With Us");

        javax.swing.GroupLayout pnlContactdetails4Layout = new javax.swing.GroupLayout(pnlContactdetails4);
        pnlContactdetails4.setLayout(pnlContactdetails4Layout);
        pnlContactdetails4Layout.setHorizontalGroup(
            pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblFacebooklogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfbID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblmaillogo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblemail)))
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblphonelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblContactinfo)
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSocialMedia4))
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblInstalogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblinstaID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlContactdetails4Layout.setVerticalGroup(
            pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblContactinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmaillogo)
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblemail)))
                .addGap(18, 18, 18)
                .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addComponent(lblPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblphone))
                    .addComponent(lblphonelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblSocialMedia4)
                .addGroup(pnlContactdetails4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFacebooklogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlContactdetails4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblinstaID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfbID)
                        .addGap(11, 11, 11)))
                .addGap(173, 173, 173))
        );

        javax.swing.GroupLayout pnlspeakwithusLayout = new javax.swing.GroupLayout(pnlspeakwithus);
        pnlspeakwithus.setLayout(pnlspeakwithusLayout);
        pnlspeakwithusLayout.setHorizontalGroup(
            pnlspeakwithusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlspeakwithusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlContactdetails4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlspeakwithusLayout.setVerticalGroup(
            pnlspeakwithusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContactdetails4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlInquaries.setBackground(new java.awt.Color(102, 102, 102));

        pnlinquariess.setBackground(new java.awt.Color(255, 255, 255));

        lblworkinghourlogo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblworkinghourlogo.setForeground(new java.awt.Color(102, 102, 102));
        lblworkinghourlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 120433.png"))); // NOI18N

        lblmaillogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 113533.png"))); // NOI18N

        lblpartnershipmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblpartnershipmail.setForeground(new java.awt.Color(153, 153, 153));
        lblpartnershipmail.setText("partnershipohlana'swears@gmail.com");

        lblworkinghours.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        lblworkinghours.setForeground(new java.awt.Color(51, 51, 51));
        lblworkinghours.setText("Working Hours");

        lblinquaries.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        lblinquaries.setForeground(new java.awt.Color(51, 51, 51));
        lblinquaries.setText("Corporate Inquiries ");

        lblpartnershipcontact.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblpartnershipcontact.setForeground(new java.awt.Color(153, 153, 153));
        lblpartnershipcontact.setText("For partnership opportunities, contact:  ");

        lblpartnership.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblpartnership.setForeground(new java.awt.Color(102, 102, 102));
        lblpartnership.setText("Email ");

        lblSaturday.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblSaturday.setForeground(new java.awt.Color(102, 102, 102));
        lblSaturday.setText("Saturday and Public Holidays  ");

        lblMontofri.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblMontofri.setForeground(new java.awt.Color(102, 102, 102));
        lblMontofri.setText("Sunday - Friday ");

        lblTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(153, 153, 153));
        lblTime.setText("9:00 AM - 7:00 PM");

        lblworkinghourlogo1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblworkinghourlogo1.setForeground(new java.awt.Color(102, 102, 102));
        lblworkinghourlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-21 120433.png"))); // NOI18N

        lblClosed.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblClosed.setForeground(new java.awt.Color(153, 153, 153));
        lblClosed.setText("Closed");

        javax.swing.GroupLayout pnlinquariessLayout = new javax.swing.GroupLayout(pnlinquariess);
        pnlinquariess.setLayout(pnlinquariessLayout);
        pnlinquariessLayout.setHorizontalGroup(
            pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinquariessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinquaries)
                    .addComponent(lblworkinghours)
                    .addGroup(pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblworkinghourlogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMontofri)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblpartnershipcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblmaillogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpartnership)
                            .addComponent(lblpartnershipmail)))
                    .addGroup(pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblworkinghourlogo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaturday)
                            .addComponent(lblClosed))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlinquariessLayout.setVerticalGroup(
            pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinquariessLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblinquaries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpartnershipcontact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblpartnership)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblpartnershipmail))
                    .addComponent(lblmaillogo1))
                .addGap(17, 17, 17)
                .addComponent(lblworkinghours)
                .addGap(18, 18, 18)
                .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblworkinghourlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblMontofri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime)))
                .addGap(18, 18, 18)
                .addGroup(pnlinquariessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlinquariessLayout.createSequentialGroup()
                        .addComponent(lblSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblClosed))
                    .addComponent(lblworkinghourlogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInquariesLayout = new javax.swing.GroupLayout(pnlInquaries);
        pnlInquaries.setLayout(pnlInquariesLayout);
        pnlInquariesLayout.setHorizontalGroup(
            pnlInquariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInquariesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlinquariess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlInquariesLayout.setVerticalGroup(
            pnlInquariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlinquariess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ContactUsLayout = new javax.swing.GroupLayout(ContactUs);
        ContactUs.setLayout(ContactUsLayout);
        ContactUsLayout.setHorizontalGroup(
            ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactUsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblcontactusSub)
                .addGap(195, 195, 195))
            .addGroup(ContactUsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContactsubheading)
                    .addGroup(ContactUsLayout.createSequentialGroup()
                        .addComponent(pnlspeakwithus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInquaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContactUsLayout.setVerticalGroup(
            ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcontactusSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContactsubheading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInquaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlspeakwithus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabPaneMain.addTab("Contact Us", ContactUs);

        pnlMainBar.setBackground(new java.awt.Color(51, 51, 51));
        pnlMainBar.setForeground(new java.awt.Color(51, 51, 51));
        pnlMainBar.setInheritsPopupMenu(true);

        lblMainBarSlogan.setBackground(new java.awt.Color(153, 153, 153));
        lblMainBarSlogan.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblMainBarSlogan.setForeground(new java.awt.Color(153, 153, 153));
        lblMainBarSlogan.setText("Style Meets Comfort");
        lblMainBarSlogan.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-12 114145.png"))); // NOI18N
        lblLogo.setText("logo");
        lblLogo.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout pnlMainBarLayout = new javax.swing.GroupLayout(pnlMainBar);
        pnlMainBar.setLayout(pnlMainBarLayout);
        pnlMainBarLayout.setHorizontalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(lblMainBarSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainBarLayout.setVerticalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblMainBarSlogan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlMainBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblcopyrightfooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcopyrightfooter.setText("Copyright © 2024 Oh-lana's Wears");
        lblcopyrightfooter.setToolTipText("");

        btnLogOut.setBackground(new java.awt.Color(102, 102, 102));
        btnLogOut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(204, 204, 204));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcopyrightfooter, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcopyrightfooter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnlLoginScreen.setBackground(new java.awt.Color(0, 0, 0));
        pnlLoginScreen.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(807, 600));

        pnlLoginLeft.setBackground(new java.awt.Color(153, 153, 153));
        pnlLoginLeft.setRequestFocusEnabled(false);

        iblloginimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-14 162010.png"))); // NOI18N
        iblloginimage.setText("jLabel1");

        iblLoginslogan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        iblLoginslogan.setForeground(new java.awt.Color(51, 51, 51));
        iblLoginslogan.setText("Define Your ");

        iblLoginsloganlook.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        iblLoginsloganlook.setForeground(new java.awt.Color(51, 51, 51));
        iblLoginsloganlook.setText("LOOK!");

        lblOhlana.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        lblOhlana.setForeground(new java.awt.Color(102, 102, 102));
        lblOhlana.setText("Oh-Lana's Wears");

        javax.swing.GroupLayout pnlLoginLeftLayout = new javax.swing.GroupLayout(pnlLoginLeft);
        pnlLoginLeft.setLayout(pnlLoginLeftLayout);
        pnlLoginLeftLayout.setHorizontalGroup(
            pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblLoginslogan)
                    .addGroup(pnlLoginLeftLayout.createSequentialGroup()
                        .addComponent(iblLoginsloganlook)
                        .addGap(42, 42, 42)
                        .addComponent(lblOhlana, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlLoginLeftLayout.createSequentialGroup()
                .addComponent(iblloginimage, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLoginLeftLayout.setVerticalGroup(
            pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblLoginslogan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblLoginsloganlook)
                    .addComponent(lblOhlana, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iblloginimage)
                .addGap(25, 25, 25))
        );

        lblLoginTitle.setBackground(new java.awt.Color(153, 153, 153));
        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblLoginTitle.setText("Sign to Oh-Lana's Wears");

        lblLoginSubTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblLoginSubTitle.setText("Please enter your login details below using this app");

        txtFldUserName.setBackground(new java.awt.Color(0, 0, 0));
        txtFldUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtFldUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "User Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtFldUserName.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUserNameActionPerformed(evt);
            }
        });

        lblLoginForgotPwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoginForgotPwd.setForeground(new java.awt.Color(153, 153, 153));
        lblLoginForgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginForgotPwd.setText("Forgot your password?");

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        pwdFldLogin.setBackground(new java.awt.Color(0, 0, 0));
        pwdFldLogin.setForeground(new java.awt.Color(102, 102, 102));
        pwdFldLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        lblLoginError.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginError.setText("jLabel1");

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addComponent(pnlLoginLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addComponent(lblLoginForgotPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblLoginSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28))
                                    .addComponent(lblLoginError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginSubTitle)
                .addGap(34, 34, 34)
                .addComponent(txtFldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginForgotPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoadingScreen.setBackground(new java.awt.Color(153, 153, 153));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(807, 600));

        pgBarSplashScreen.setStringPainted(true);
        pgBarSplashScreen.setForeground(new java.awt.Color(0, 0, 0));

        lblLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoading.setText("Loading...");

        Logoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CothesApp/resources/Screenshot 2024-12-12 114336.png"))); // NOI18N
        Logoo.setText("jLabel2");

        javax.swing.GroupLayout pnlLoadingScreenLayout = new javax.swing.GroupLayout(pnlLoadingScreen);
        pnlLoadingScreen.setLayout(pnlLoadingScreenLayout);
        pnlLoadingScreenLayout.setHorizontalGroup(
            pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingScreenLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoading)
                            .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                        .addComponent(Logoo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        pnlLoadingScreenLayout.setVerticalGroup(
            pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logoo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoading)
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Method to set up the CardLayout and add panels

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadingScreen");

    }

    //Method to initialize data, including Clothes list and table
    private void initializeData(){
        clothesList = new ArrayList();
        registerClothes(new ClothesModel(1234, "Half Shirt", "Shirt", "Blue", 15, 25000), true);
        registerClothes(new ClothesModel(1589, "Half Pant", "Pant", "Black", 20, 40000), true);
        registerClothes(new ClothesModel(4567, "Off-sholder Sweater", "Sweater", "Red", 5, 15000), true);
        registerClothes(new ClothesModel(8974, "Grunch pant", "Pant", "Blue", 10, 20000), true);
        registerClothes(new ClothesModel(6986, "Over-size hoodie", "Hoodie", "Brown", 8, 19000), true);
    }

    // Method to simulate loading progress
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarSplashScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }

    // Method to switch screens
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = txtFldUserName.getText();
        String password = new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("Oh-lana's") || !password.equals("Oh-lana's")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }

    }//GEN-LAST:event_btnLoginActionPerformed
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        pwdFldLogin.setText("");
        txtFldUserName.setText("");
        loadScreen("LoginScreen"); // Load the main screen

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtFldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUserNameActionPerformed

    }//GEN-LAST:event_txtFldUserNameActionPerformed


    private void txtFldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProductNameActionPerformed
        // Retrieve the text from the product name text field
        String productName = txtFldProductName.getText();

        // Check if the product name is empty
        if (productName.isEmpty()) {
            // Show an error message if no input is provided
            JOptionPane.showMessageDialog(this, "Product name cannot be empty!", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else if (productName.length() < 3) {
            // Show a warning if the product name is too short
            JOptionPane.showMessageDialog(this, "Product name must be at least 3 characters long.", "Input Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            // Display a success message for valid input
            JOptionPane.showMessageDialog(this, "Product '" + productName + "' added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtFldProductNameActionPerformed


    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblClothes.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(pnlAdminControl, "Please select a clothes item to update.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;}
        try {
            int productCode = Integer.parseInt(txtFldProductCode.getText());
            String productName = txtFldProductName.getText();
            String productType = txtFldProductType.getText();
            String color = txtFldColor.getText();
            int stock = Integer.parseInt(txtFldStock.getText());
            double price = Double.parseDouble(txtFldPrice.getText());

            ClothesModel updatedClothes = new ClothesModel(productCode, productName, productType, color, stock, price);

            // Update clothesList
            clothesList.set(selectedRow, updatedClothes);

            // Update table
            DefaultTableModel model = (DefaultTableModel) tblClothes.getModel();
            model.setValueAt(productCode, selectedRow, 0);
            model.setValueAt(productName, selectedRow, 1);
            model.setValueAt(productType, selectedRow, 2);
            model.setValueAt(color, selectedRow, 3);
            model.setValueAt(stock, selectedRow, 4);
            model.setValueAt(price, selectedRow, 5);

            JOptionPane.showMessageDialog(pnlAdminControl, "Clothes updated successfully!", "Update Success", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(pnlAdminControl, "Invalid input. Please check your entries.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    Validationutil validator = new Validationutil();
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // Prompt the user for the product code to delete
        String deleteCode = JOptionPane.showInputDialog(pnlMainScreen, "Enter product Code:");
        if (deleteCode == null || deleteCode.isEmpty()) {
            JOptionPane.showMessageDialog(pnlMainScreen, "Empty box. Please enter a value.", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int rcode = Integer.parseInt(deleteCode);
                boolean found = false; // Flag to check if product exists

                // Using iterator to safely remove from the list
                for (Iterator<ClothesModel> iterator = clothesList.iterator(); iterator.hasNext(); ) {
                    ClothesModel product = iterator.next();
                    if (product.getProductcode() == rcode) {
                        iterator.remove(); // Remove the product safely
                        JOptionPane.showMessageDialog(pnlMainScreen, "Successfully removed product!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        found = true; // Mark as found
                        break; // Exit loop after removal
                    }
                }

                if (!found) {
                    JOptionPane.showMessageDialog(pnlMainScreen, "Product not found!", "Alert", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Update the table model after deletion
                    updateTableModel();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(pnlMainScreen, "Product code should be a number!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    // Helper method to refresh the table model
    private void updateTableModel() {
        DefaultTableModel model = (DefaultTableModel) tblClothes.getModel();
        model.setRowCount(0); // Clear existing rows

        // Populate the table with updated data
        for (ClothesModel product : clothesList) {
            model.addRow(new Object[] {
                    product.getProductcode(),
                    product.getProductname(),
                    product.getProducttype(),
                    product.getColor(),
                    product.getStock(),
                    product.getPrice()
            });
        }
    }



  //Method to add clothes and populate the table  
    private void registerClothes(ClothesModel clothes, boolean update) {
        clothesList.add(clothes);
        DefaultTableModel model = (DefaultTableModel) tblClothes.getModel();
        model.addRow(new Object[]{
            clothes.getProductcode(), clothes.getProductname(), clothes.getProducttype(),
            clothes.getColor(), clothes.getStock(), clothes.getPrice()          
        });

    }



    private void clearFields() {
        txtFldProductCode.setText("");
        txtFldProductName.setText("");
        txtFldProductType.setText("");
        txtFldColor.setText("");
        txtFldStock.setText("");
        txtFldPrice.setText("");
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String productcode = txtFldProductCode.getText();
        String productname = txtFldProductName.getText();
        String producttype = txtFldProductType.getText();
        String color = txtFldColor.getText();
        String stock = txtFldStock.getText();
        String price = txtFldPrice.getText();

        if (productcode.isEmpty() || productname.isEmpty() || producttype.isEmpty() || color.isEmpty() || stock.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(pnlAdminControl, "Please enter all details of clothes.", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Validationutil validator = new Validationutil();

                // Validate each field using the validator
                if (!validator.isValidProductCode(productcode)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Product Code! Must be exactly 4 digits.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!validator.isValidProductName(productname)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Product Name! Must contain only letters and spaces.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!validator.isValidProductType(producttype)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Product Type! Must be one of: Shirt, Pants, Dress, Jacket, Sweater.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!validator.isValidColor(color)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Color! Must contain only letters.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!validator.isValidStock(stock)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Stock! Must be a number between 0 and 1000.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!validator.isValidPrice(price)) {
                    JOptionPane.showMessageDialog(pnlAdminControl, "Invalid Price! Must be between 0.01 and 10000.00.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int pcode = Integer.parseInt(productcode);
                int pstock = Integer.parseInt(stock);
                double pprice = Double.parseDouble(price);

                // Checks if clothes already exist
                boolean clothesExists = false;
                for (ClothesModel clothes : clothesList) {
                    if (clothes.getProductcode() == pcode || clothes.getProductname().equals(productname)) {
                        clothesExists = true;
                        break;
                    }
                }

                // Display pop up box if clothes already exists
                if(clothesExists){
                    JOptionPane.showMessageDialog(pnlAdminControl, "The Clothes already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    //create new clothesModel Object
                    ClothesModel clothes = new ClothesModel(pcode,productname, producttype, color, pstock,pprice);
                    registerClothes(clothes, false);

                }

            }catch (NumberFormatException n){
                JOptionPane.showMessageDialog(pnlAdminControl, "Invalid input. Please enter valid numbers.", "Information", JOptionPane.INFORMATION_MESSAGE);

            }

        }



    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFldProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldProductCodeActionPerformed

    private void txtFldProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProductTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldProductTypeActionPerformed

    private void txtFldColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldColorActionPerformed

    private void txtFldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldStockActionPerformed

    private void txtFldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldPriceActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OhlanasWears.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OhlanasWears.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OhlanasWears.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OhlanasWears.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OhlanasWears().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel ContactUs;
    private javax.swing.JPanel Homepage;
    private javax.swing.JLabel Logoo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel iblLoginslogan;
    private javax.swing.JLabel iblLoginsloganlook;
    private javax.swing.JLabel iblloginimage;
    private javax.swing.JScrollPane jScrollPaneClothestable;
    private javax.swing.JLabel lblClosed;
    private javax.swing.JLabel lblContactinfo;
    private javax.swing.JLabel lblContactsubheading;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacebooklogo;
    private javax.swing.JLabel lblInstalogo;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginForgotPwd;
    private javax.swing.JLabel lblLoginSubTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMainBarSlogan;
    private javax.swing.JLabel lblMontofri;
    private javax.swing.JLabel lblOhlana;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblProductManagement;
    private javax.swing.JLabel lblSaturday;
    private javax.swing.JLabel lblSocialMedia4;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblaboutus;
    private javax.swing.JLabel lblaboutusHeading;
    private javax.swing.JLabel lblaboutusSubHeading;
    private javax.swing.JLabel lblcontactusSub;
    private javax.swing.JLabel lblcopyrightfooter;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfbID;
    private javax.swing.JLabel lblfifthline;
    private javax.swing.JLabel lblfourthline;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lblhomebest;
    private javax.swing.JLabel lblhomecollection;
    private javax.swing.JLabel lblhomeimage;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblinquaries;
    private javax.swing.JLabel lblinstaID;
    private javax.swing.JLabel lblmaillogo;
    private javax.swing.JLabel lblmaillogo1;
    private javax.swing.JLabel lblparag;
    private javax.swing.JLabel lblparaglinefour;
    private javax.swing.JLabel lblparaglinethree;
    private javax.swing.JLabel lblparaglinetwo;
    private javax.swing.JLabel lblpartnership;
    private javax.swing.JLabel lblpartnershipcontact;
    private javax.swing.JLabel lblpartnershipmail;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblphonelogo;
    private javax.swing.JLabel lblsecondline;
    private javax.swing.JLabel lblsecondparagraph;
    private javax.swing.JLabel lblsecparagLinethree;
    private javax.swing.JLabel lblsecparagLinetwo;
    private javax.swing.JLabel lblsubheading;
    private javax.swing.JLabel lbltabClothes;
    private javax.swing.JLabel lblthirdline;
    private javax.swing.JLabel lblworkinghourlogo;
    private javax.swing.JLabel lblworkinghourlogo1;
    private javax.swing.JLabel lblworkinghours;
    private javax.swing.JProgressBar pgBarSplashScreen;
    private javax.swing.JPanel pnlAdminControl;
    private javax.swing.JPanel pnlClothes;
    private javax.swing.JPanel pnlContactdetails4;
    private javax.swing.JPanel pnlInquaries;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlLoginLeft;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainBar;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlinquariess;
    private javax.swing.JPanel pnlspeakwithus;
    private javax.swing.JPasswordField pwdFldLogin;
    private javax.swing.JTabbedPane tabPaneClothes;
    private javax.swing.JTabbedPane tabPaneMain;
    private javax.swing.JTable tblClothes;
    private javax.swing.JTextField txtFldColor;
    private javax.swing.JTextField txtFldPrice;
    private javax.swing.JTextField txtFldProductCode;
    private javax.swing.JTextField txtFldProductName;
    private javax.swing.JTextField txtFldProductType;
    private javax.swing.JTextField txtFldStock;
    private javax.swing.JTextField txtFldUserName;
    // End of variables declaration//GEN-END:variables
}
